### ISSUE TITLE
Request for Vast 3.0 function

### ISSUE THREAD

**Issue by macoybarayan** [sokil/php-vast#18]
Hi,

I find your codes so helpful. I'm currently developing an ad pod type ad which is supported on Vast 3.0 but the current code is missing a function for adding sequence eg <ad sequence='n'> which is necessary for ad pod to work.

Can you add this code to the Ads.php on your next release? Sokil\Vast\Ad

 public function setSequence($id)
    {
        $this->_domElement->setAttribute('sequence', $id);
        return $this;
    }

Hope I can get your response as soon as possible.. Thank you :)

**Comment by sokil** [comment]
Hi. You may do this yourself. Just fork, modify and send pull request.

Maybe you are looking for this? 

https://github.com/sokil/php-vast/blob/0526f7e36f657bbffee8f70d8583884f0b05aea8/src/Ad/AbstractAdNode.php#L74-L96
