### ISSUE TITLE
getValuesOfArrayNode() broken

### ISSUE THREAD

**Issue by oliverspecht** [sokil/php-vast#19]
When using AbstractAdNode::getDomElement() (using AbstractNode::getValuesOfArrayNode()) an error is thrown because getDomElement() does return DOMText instead of DOMElement.

When changing

`    protected function getDomElement()
    {
        return $this->adDomElement->firstChild;
    }
`

to 

`    protected function getDomElement()
    {
        return $this->adDomElement;
    }
`

it works.

In the following call to AbstractNode::getValuesOfArrayNode() an iteration is done but index 0 is used in every iteration instead of $i, so the iteration is supposed to look like this I think:

`        for ($i = 0; $i < $domElements->length; $i++) {
            $values[$i] = $domElements->item($i)->nodeValue;
        }
`

What do you think? Are my assumptions correct? Thanks!

**Comment by sokil** [comment]
Iteration bu index 0 fixed.

```
Error is thrown because getDomElement() does return DOMText instead of DOMElement
```

May you show me the code and xml to reproduce?

**Comment by oliverspecht** [comment]
Great, thx. 

Here is the code to reproduce:
<?xml version="1.0" encoding="utf-8"?>
    <VAST version="2.0">
      <Ad id="ID">
        <InLine>
          <AdSystem><![CDATA[AdSystem]]></AdSystem>
          <AdTitle><![CDATA[Title]]></AdTitle>
          <Description><![CDATA[Description]]></Description>
          <Impression id="imp1"><![CDATA[imp1]]></Impression>
          <Impression id="imp2"><![CDATA[imp2]]></Impression>
          <Impression id="imp3"><![CDATA[imp3]]></Impression>
          <Impression id="imp4"><![CDATA[imp4]]></Impression>
          <Creatives>
            <Creative id="cre1">
              <Linear>
                <Duration>00:00:10</Duration>
                <TrackingEvents>
                  <Tracking event="start">
                    <![CDATA[trackStart]]></Tracking>
                  <Tracking event="firstQuartile">
                    <![CDATA[trackFirstQuartile]]></Tracking>
                  <Tracking event="midpoint">
                    <![CDATA[trackMidPoint]]></Tracking>
                </TrackingEvents>
                <VideoClicks>
                  <ClickTracking><![CDATA[trackClick1]]></ClickTracking>
                  <ClickTracking><![CDATA[trackClick2]]></ClickTracking>
                  <ClickTracking><![CDATA[trackClick3]]></ClickTracking>
                </VideoClicks>
                <MediaFiles>
                  <MediaFile id="1" width="640" height="360" bitrate="670" type="video/mp4" delivery="progressive"
                             maintainAspectRatio="true" scalable="true">
                    <![CDATA[https://mediaFile1.url]]></MediaFile>
                  <MediaFile id="2" width="640" height="360" bitrate="670" type="video/mp4" delivery="progressive"
                             maintainAspectRatio="true" scalable="true">
                    <![CDATA[https://mediaFile2.url]]></MediaFile>
                  <MediaFile id="3" width="640" height="360" bitrate="670" type="video/mp4" delivery="progressive"
                             maintainAspectRatio="true" scalable="true">
                    <![CDATA[https://mediaFile3.url]]></MediaFile>
                </MediaFiles>
              </Linear>
            </Creative>
          </Creatives>
        </InLine>
      </Ad>
    </VAST>

*Edit* 
Just checked, the error occurs too if you use the XML example from the start page. I read the XML with Factory::fromString()

*Edit again*
Would be great if the DOMelement objects would be returned somehow as no access to attributes is possible now.

**Comment by sokil** [comment]
bug fixed.

> Would be great if the DOMelement objects would be returned somehow as no access to attributes is possible now.

It's wrong because getter, which return \DOMElement, shows internal implementation of library. If XML engine will change from DOM to something else, it will be change without backward compatibility. Also library has relations from dom to objects, and modification of DOM outside library may add inconsistent state of DOM. 

If you need some new features, just send PRs )

**Comment by oliverspecht** [comment]
Thx for the quick response!

> It's wrong because getter, which return \DOMElement, shows internal implementation of library.

Alright, I get that. I will check, if I can work without that feature.
