### ISSUE TITLE
VASTAdTagURI Feature

### ISSUE THREAD

**Issue by Psiiirus** [sokil/php-vast#2]
Hiya , 
are there any plans to implement the **VASTAdTagURI** tag?

 #Cheers,
Toni

**Comment by sokil** [comment]
No, but this is open source so i will glad for any contribution )

**Comment by Psiiirus** [comment]
i see ^^....currently playing around with it but unfortunately the "private" vars driving me crazy ;-)

...i think i will go with a fork now

thx

**Comment by sokil** [comment]
This habit thrown long tima ago, but already in code. I am shamed ) happy to get contribution for that too))

**Comment by sokil** [comment]
by the way v.0.3.1 in master. thank you
