### ISSUE TITLE
Add extra attr in tags

### ISSUE THREAD

**Issue by farshidboroomand** [sokil/php-vast#30]
i need to set some extra attr to Creative tag as below :

<Creative id="THE ID" adId="pre">
.....
<Creative/>

where can i set the items in my laravel application. 

also i need to define specific events instead of fullScreen & exit fullscreen.

**Comment by sokil** [comment]
hi.

If you need some extra tag you need to overload some classes. 

There is discussion in #29 but author of PR do not responds. You may add your pull request.

**Comment by sokil** [comment]
You may try to use currently undocummented feature with ElementBuilder

```php
class CustomVastDialectElementBuilder extends ElementBuilder
{
    // override there some elements you need with your own classes
}

$elementBuilder = new CustomVastDialectElementBuilder();
$fanctory = new Factory($elementBuilder);
```

Now you create object model of VAST document with your own dialect, where you can add anythink you want

**Comment by sokil** [comment]
Custom element and attribute creation allowed since [0.6](https://github.com/sokil/php-vast/releases/tag/0.6)
