### ISSUE TITLE
Extend?

### ISSUE THREAD

**Issue by sokil** [sokil/php-vast#5]
http://stackoverflow.com/questions/33044788/extending-a-class-that-has-been-instantiated-without-new

**Comment by dorantor** [comment]
I have refactored your lib to move away from static methods, so this issue should be partially solved, but it's breaking backwards compatibility in terms how `$document` should created. Everything else should be the same. And some functionality for Wrapper(my current focus) added.
Not sure how PR should be sent in this case. Probably it should be different major version. Anyway, please take a look: https://github.com/dorantor/php-vast
and let me know if like it a would like as PR.

**Comment by sokil** [comment]
Custom element and attribute creation allowed since [0.6](https://github.com/sokil/php-vast/releases/tag/0.6)
